version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4
        environment:
          PGHOST: 127.0.0.1
          NODE_ENV: test
      - image: circleci/postgres:10.2-alpine-postgis
        environment:
          POSTGRES_DB: hiking_club
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: postgres

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
        
      - run: npm run db:init && npm test


